version: '3'

services:
  python-service:
    container_name: python
    restart: always
    image: REGISTRY:TAG-python
    ports:
      - 8080:5000

  php-service:
    container_name: php
    restart: always
    image: REGISTRY:TAG-php
    ports:
      - 8090:80
 
  nginx-service:
    container_name: nginx
    restart: always
    image: REGISTRY:TAG-nginx
    ports:
      - 80:80
